Default: &defaults
  database: aci-webapp.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: aci-webapp_test.sqlite3
  <<: *defaults

Staging:
  database: aci-webapp_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: aci-webapp_production.sqlite3
  poolsize: 100
  <<: *defaults
